# Generated by Django 4.0.5 on 2022-06-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_options_project_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='info',
        ),
    ]
